### ISSUE TITLE
kango.localforage Backbone: collection.fetch() does return nothing

### ISSUE THREAD

**Issue by dharma-guardian** [iamolivinius/gulpicRose#2]
When there is a collection in storage collection.fetch() will not fetch the models. 
`kango.invokeAsyncCallback('localforage.getItem', collection.sync.localforageKey, function(err, data) {`
returns `data`as `undefined` although there is a collection with the a corresponding key stored.

Issue should be in https://github.com/iamolivinius/kango-localForage-backbone

**Comment by dharma-guardian** [comment]
`collection.fetch({reset: true});` doesn't do the trick either

**Comment by iamolivinius** [comment]
Downgrade to localforage fixed this

**Comment by iamolivinius** [comment]
v0.9.2
